# Generated by Django 5.1.2 on 2024-10-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_blacklist_email_blacklist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='ip',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
