# Generated by Django 5.1.2 on 2024-11-04 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_myblacklist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklist',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='blacklist',
            name='url',
        ),
        migrations.CreateModel(
            name='CapturedPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(max_length=15)),
                ('url', models.CharField(max_length=255)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='blacklist',
            name='capturedpacket_entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.capturedpacket'),
        ),
    ]
