# Generated by Django 5.1.2 on 2024-11-04 13:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_capturedpacket_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='capturedpacket',
            unique_together={('user', 'ip'), ('user', 'ip', 'url'), ('user', 'url')},
        ),
    ]
