# Generated by Django 4.1.3 on 2024-11-05 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0010_remove_myblacklist_added_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='myblacklist',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='myblacklist',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='myblacklist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='capturedpacket_entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.capturedpacket'),
        ),
    ]
