# Generated by Django 4.1.3 on 2024-11-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_myblacklist_unique_together_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='myblacklist',
            constraint=models.UniqueConstraint(fields=('blacklist_entry', 'user'), name='unique_blacklist_user'),
        ),
    ]
