services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 --workers 3 demo.wsgi:application
    volumes:
      - .:/app
      - static_volume:/app/static  # <-- Bind the static volume for collected static files
      - media_volume:/app/media
    expose:
      - "8000"  # Expose port for Caddy

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - static_volume:/app/static  # <-- bind the static volume
      - media_volume:/app/media  # <-- bind the media volume
    depends_on:
      - web

volumes:
  caddy_data:
  caddy_config:
  static_volume:
  media_volume: