# docker-compose file managing Nginx and the application
# Loading some variables from the .env file:
#   - DOMAIN: DNS domain name
#   - EMAIL: Maintainer email
#   - APP_FOLDER: Directory containing the application
#   - DJANGO_APP: Flask entrypoint
#   - DJANGO_ENV: Django environment


services:
  nginx:
    build:
      context: ./nginx
      args:
        DOMAIN: ${DOMAIN}
        EMAIL: ${EMAIL}
        DJANGO: application
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - application

  application:
    build: ./${APP_FOLDER}
    command: gunicorn --bind 0.0.0.0:${DJANGO_APP_PORT} --workers 3 ${DJANGO_APP}:application
    environment:
      - DJANGO_ENV=${DJANGO_ENV}
    ports:
    - "${DJANGO_APP_PORT}:${DJANGO_APP_PORT}"
