# Generated by Django 5.1.2 on 2024-11-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_blacklist_ip_remove_blacklist_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturedpacket',
            name='ip',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='capturedpacket',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
