# Generated by Django 5.1.2 on 2024-11-04 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_capturedpacket_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklist',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='myblacklist',
            unique_together={('blacklist_entry',)},
        ),
        migrations.RemoveField(
            model_name='myblacklist',
            name='user',
        ),
    ]
