# Generated by Django 5.1.2 on 2024-11-04 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_blacklist_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myblacklist',
            name='added_at',
        ),
    ]
