# Generated by Django 5.1.2 on 2024-11-04 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_remove_myblacklist_added_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='myblacklist',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='myblacklist',
            name='added_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='myblacklist',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='myblacklist',
            unique_together={('blacklist_entry', 'user')},
        ),
    ]
