services:
  db:
    container_name: mysql-container
    image: mysql:8.0.39
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
      - MYSQL_USER=${SQL_USER}
      - MYSQL_PASSWORD=${SQL_PASSWORD}
      - MYSQL_DATABASE=${SQL_DATABASE}
    ports:
      - 3306:3306

  web:
    container_name: django-web-container
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/usr/src/app/static
    env_file:
      - ./.env
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db
    restart: always

  caddy:
    container_name: caddy-container
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - static_volume:/usr/src/app/static
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web
    restart: always

volumes:
  caddy_data:
  caddy_config:
  mysql_data:
  static_volume:  